// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XCX1nCtpwWBGyw67HhuMy1p8BtnIr-A',
    appId: '1:41319614717:web:c647397cca717c2d611694',
    messagingSenderId: '41319614717',
    projectId: 'smarthome-app-3ea44',
    authDomain: 'smarthome-app-3ea44.firebaseapp.com',
    databaseURL: 'https://smarthome-app-3ea44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-app-3ea44.appspot.com',
    measurementId: 'G-42LTHNW8EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6iuMmG-Tn1KQcmpHNW_kd2ULpXSOiLk',
    appId: '1:41319614717:android:9af01b347a729aef611694',
    messagingSenderId: '41319614717',
    projectId: 'smarthome-app-3ea44',
    databaseURL: 'https://smarthome-app-3ea44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-app-3ea44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDP7yvDelIyHNNrlUxJ1ztn8GabePVUdk',
    appId: '1:41319614717:ios:ac5498babbd061cc611694',
    messagingSenderId: '41319614717',
    projectId: 'smarthome-app-3ea44',
    databaseURL: 'https://smarthome-app-3ea44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-app-3ea44.appspot.com',
    iosClientId: '41319614717-a0srk9ck8aj1hupbb01j7hgoc7eg17ro.apps.googleusercontent.com',
    iosBundleId: 'com.smps.smarthomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDP7yvDelIyHNNrlUxJ1ztn8GabePVUdk',
    appId: '1:41319614717:ios:a97e6a614ef8741b611694',
    messagingSenderId: '41319614717',
    projectId: 'smarthome-app-3ea44',
    databaseURL: 'https://smarthome-app-3ea44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-app-3ea44.appspot.com',
    iosClientId: '41319614717-t2bjbk409002kqhls38icbb3l04t0hei.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthomeApp',
  );
}
